use healthcare;
alter table`cleaned data healthcare`rename to healthcare;
select * from healthcare;
select * from healthcare limit 10;
DESCRIBE healthcare;
select count(*) as total_patient from healthcare;
select distinct `medical condition` from healthcare;
select distinct `hospital`from healthcare;
select gender,count(*) as total from healthcare group by gender;
select`blood type`,count(*) as total from healthcare group by`blood type`;
select min(age) as minimum_age,max(age)as maximum_age from healthcare; 
select * from healthcare where gender = 'female';
select *  from healthcare where age > 60;
select * from healthcare where`medical condition`='diabetes';
select * from healthcare where `admission type`='emergency';
SELECT * FROM healthcare WHERE `Test Results` = 'Abnormal';
select * from healthcare where `blood type`='o+';
select * from healthcare where hospital='white-white';
select * from healthcare where medication ='ibuprofen';